### ISSUE TITLE
Move shaders to Resources folder

### ISSUE THREAD

**Issue by RomanFrom710** [Svrf/svrf-unity#14]
It turned out it's possible to add shaders to the `Resources` folder. It shouldn't be necessary to manually add our shaders to the build in that case.

Need to move shaders to this folder and test that everything still works. Also update the docs (either remove the section about adding shaders to the build or mark it as deprecated).

**Comment by brentchow** [comment]
Sounds like this should be a pretty easy ticket to accomplish. 

I think we document it as a breaking change in the Release notes. We can mark it as deprecated if you're concerned about leaving it in the docs for people using old versions of the SDK.

**Comment by RomanFrom710** [comment]
If we leave our shader variants file, it won't be a breaking change: it'll still be included in build in existent projects, but developers will be able to remove it.

Also need to check what happens with existing project if we remove shader variants file. Probably there wouldn't be any errors and Unity will just ignore it.

**Comment by RomanFrom710** [comment]
- Updated [example app](https://github.com/Svrf/svrf-api/tree/master/examples/ARCoreUnityDemo).
- Updated [blog post](https://blog.svrf.com/how-to-build-a-3d-face-filter-app-for-unity-and-arcore/) (removed the part about including shaders since the blog post readers will always download the newest version).
- Removed disclaimer about required shaders from the [Loading 3D Models](https://docs.svrf.com/docs/unity-loading-model) page.
- Added deprecated warning to the [Including Shaders](https://docs.svrf.com/docs/unity-including-shaders) page. I think we may delete this page completely in the nearest future.
