### ISSUE TITLE
Add coroutine information to docs

### ISSUE THREAD

**Issue by RomanFrom710** [Svrf/svrf-unity#7]
Add note that all our async methods can be used as coroutines with a little code snippet.

I think the [Async operations](https://docs.svrf.com/docs/unity-making-api-requests#section-async-operations) section is the best place for that.

**Comment by RomanFrom710** [comment]
Updated docs: https://docs.svrf.com/docs/unity-making-api-requests#section-running-async-operations-as-coroutines

**Comment by brentchow** [comment]
checked and made some small grammatical fixes. closing :)
