### ISSUE TITLE
Add in editor asset search and previewer to docs

### ISSUE THREAD

**Issue by RomanFrom710** [Svrf/svrf-unity#8]
Add information about https://github.com/Svrf/svrf-unity/issues/3 when it's ready to the docs.

I'm not sure to which page, probably create a separate page for it? @brentchow

**Comment by brentchow** [comment]
Search and preview in Editor

**Comment by brentchow** [comment]
I renamed this ticket because store implies that these assets are for sale, but they're for free. I don't want that confusing anyone looking at tickets :)

**Comment by RomanFrom710** [comment]
Updated [Loading 3D Models in Unity](https://docs.svrf.com/docs/unity-loading-model) and added [Assets Viewer in Unity](https://docs.svrf.com/docs/unity-assets-viewer) sections.

**Comment by brentchow** [comment]
Reviewed and updated. Closing ticket.
